# Dependencies
markdown: kramdown
kramdown:
    input: GFM
highlighter: pygments
gems: [jekyll-paginate]

# Permalinks
permalink: pretty
relative_permalinks: false

# Setup
title:            footle
tagline:          'Brad Greenlee writes here'
description:      '(intr.v.) 1. To waste time; trifle. 2. To talk nonsense. (n.) Nonsense; foolishness'
url:              http://footle.org
baseurl:          /

author:
  name:           'Brad Greenlee'
  url:            https://twitter.com/bgreenlee
  email:          brad@footle.org

paginate:         5

lsi:              true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bgreenlee/bgreenlee.github.io

#include: ['_pages']

# Collections
collections:
    tags:
        output: true
        permalink: /tag/:path/
    pages:
        output: true
        permalink: /:path/
