# Dependencies
markdown: kramdown
kramdown:
    input: GFM
plugins: [jekyll-paginate, jekyll-gist, jekyll-archives]
include: [.well-known]
exclude: [vendor,Rakefile,Gemfile,Gemfile.lock]

# Permalinks
permalink: pretty
relative_permalinks: false

# Setup
title:            footle
tagline:          'Brad Greenlee writes here'
description:      '(intr.v.) 1. To waste time; trifle. 2. To talk nonsense. (n.) Nonsense; foolishness'
url:              https://footle.org
baseurl:          https://footle.org
timezone:         "America/Los_Angeles"
author:
  name:           'Brad Greenlee'
  url:            https://fiasco.social/@brad
  email:          brad@footle.org

paginate:         5

lsi:              true

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bgreenlee/bgreenlee.github.io

#include: ['_pages']

# Collections
collections:
    tags:
        output: true
        permalink: /tag/:path/
    pages:
        output: true
        permalink: /:path/
