#!/usr/bin/env ruby

# Based on https://gist.github.com/604999
# Script to create a jekyll blog post using a template. It takes two input
# parameters, the post type, and the title of the post.
#
# Example:
# $ blog link "helper script to create new posts using jekyll"

ROOT_DIR = File.join(File.dirname(__FILE__), '..')
TEMPLATE_DIR = File.join(ROOT_DIR, "_templates")
TARGET_DIR = File.join(ROOT_DIR, "_posts")

if ARGV.length < 2
    puts "Usage: #{$0} <post-type> <title>"
    exit
end

type = ARGV[0]
title = ARGV[1]

# normalize the title to create the filename
filename = title.downcase.gsub(' ','-').gsub(/[^\w-]/,'')
filename = "#{ Time.now.strftime('%Y-%m-%d') }-#{filename}.md" 
filepath = File.join(TARGET_DIR, filename)

# Create a copy of the template with the title replaced
new_post = File.read(File.join(TEMPLATE_DIR, "#{type}.md"))
new_post.gsub!(/\{\{\s*TITLE\s*\}\}/, title)
new_post.gsub!(/\{\{\s*DATE\s*\}\}/, Time.now.strftime("%Y-%m-%d %H:%M:%S %z"))


# Write out the file to the target directory
new_post_file = File.open(filepath, 'w')
new_post_file.puts new_post
new_post_file.close

#system("#{ENV['EDITOR']} #{filepath}")
system("open #{filepath} -a /Applications/Byword.app")
